{{- if .Values.open5gs.amf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: amf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: {{ .Values.open5gs.amf.service.type }}
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
    - port: 38412
      targetPort: 38412
      {{- if eq .Values.open5gs.amf.service.type "NodePort" }}
      nodePort: {{ .Values.open5gs.amf.service.ngap.nodePort }}
      {{- end }}
      protocol: SCTP
      name: ngap
  selector:
    app: amf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: amf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.amf.replicas }}
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-amfd"]
        args: ["-c", "/etc/open5gs/amf.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        - containerPort: 38412
          name: ngap
          protocol: SCTP
        volumeMounts:
        - name: amf-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.amf.resources }}
        resources:
          {{- toYaml .Values.open5gs.amf.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: amf-config
        configMap:
          name: amf-config
{{- end }}
