{{- if .Values.open5gs.ausf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ausf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
  selector:
    app: ausf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ausf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.ausf.replicas }}
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
      - name: ausf
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-ausfd"]
        args: ["-c", "/etc/open5gs/ausf.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        volumeMounts:
        - name: ausf-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.ausf.resources }}
        resources:
          {{- toYaml .Values.open5gs.ausf.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: ausf-config
        configMap:
          name: ausf-config
{{- end }}
