{{- if .Values.open5gs.bsf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bsf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: bsf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
  selector:
    app: bsf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: bsf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.bsf.replicas }}
  selector:
    matchLabels:
      app: bsf
  template:
    metadata:
      labels:
        app: bsf
    spec:
      containers:
      - name: bsf
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-bsfd"]
        args: ["-c", "/etc/open5gs/bsf.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        volumeMounts:
        - name: bsf-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.bsf.resources }}
        resources:
          {{- toYaml .Values.open5gs.bsf.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: bsf-config
        configMap:
          name: bsf-config
{{- end }}
