{{- if .Values.open5gs.nrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: {{ .Values.global.namespace }}
data:
  nrf.yaml: |
    logger:
      level: info

    nrf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: {{ include "open5gs-5g.serviceFQDN" (dict "name" "nrf" "root" .) }}
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
{{- end }}
