{{- if .Values.open5gs.nssf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nssf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nssf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
  selector:
    app: nssf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nssf
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.nssf.replicas }}
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
    spec:
      containers:
      - name: nssf
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-nssfd"]
        args: ["-c", "/etc/open5gs/nssf.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        volumeMounts:
        - name: nssf-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.nssf.resources }}
        resources:
          {{- toYaml .Values.open5gs.nssf.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: nssf-config
        configMap:
          name: nssf-config
{{- end }}
