{{- if .Values.open5gs.nssf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-config
  namespace: {{ .Values.global.namespace }}
data:
  nssf.yaml: |
    logger:
      level: info

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: {{ include "open5gs-5g.serviceFQDN" (dict "name" "nssf" "root" .) }}
        client:
          nrf:
            - uri: http://{{ include "open5gs-5g.serviceFQDN" (dict "name" "nrf" "root" .) }}:7777
          nsi:
            - uri: http://{{ include "open5gs-5g.serviceFQDN" (dict "name" "nrf" "root" .) }}:7777
              s_nssai:
                sst: 1
{{- end }}
