{{- if .Values.open5gs.udm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: {{ .Values.global.namespace }}
  labels:
    app: udm
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
  selector:
    app: udm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: {{ .Values.global.namespace }}
  labels:
    app: udm
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.udm.replicas }}
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
      - name: udm
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-udmd"]
        args: ["-c", "/etc/open5gs/udm.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        volumeMounts:
        - name: udm-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.udm.resources }}
        resources:
          {{- toYaml .Values.open5gs.udm.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: udm-config
        configMap:
          name: udm-config
{{- end }}
