{{- if .Values.open5gs.udr.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: {{ .Values.global.namespace }}
data:
  udr.yaml: |
    logger:
      level: info

    db_uri: mongodb://{{ include "open5gs-5g.serviceFQDN" (dict "name" "mongodb" "root" .) }}/open5gs

    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: {{ include "open5gs-5g.serviceFQDN" (dict "name" "udr" "root" .) }}
        client:
          nrf:
            - uri: http://{{ include "open5gs-5g.serviceFQDN" (dict "name" "nrf" "root" .) }}:7777
{{- end }}
