{{- if .Values.open5gs.udr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: udr
  namespace: {{ .Values.global.namespace }}
  labels:
    app: udr
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: sbi
  selector:
    app: udr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: {{ .Values.global.namespace }}
  labels:
    app: udr
    {{- include "open5gs-5g.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.open5gs.udr.replicas }}
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
      - name: udr
        image: "{{ .Values.images.open5gs.repository }}:{{ .Values.images.open5gs.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/open5gs-udrd"]
        args: ["-c", "/etc/open5gs/udr.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
          protocol: TCP
        volumeMounts:
        - name: udr-config
          mountPath: /etc/open5gs
        {{- if .Values.open5gs.udr.resources }}
        resources:
          {{- toYaml .Values.open5gs.udr.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: udr-config
        configMap:
          name: udr-config
{{- end }}
